import React from 'react';
import './TerminosYCondiciones.css';
import Head from '../Head/Head';
import Footer from '../Footer/Footer';

const TerminosYCondiciones = () => {
  return ( 
    <div>
      <Head />
      <div><h3 className="title">Términos y condiciones de uso del Sitio</h3></div>
      <p className="stylePa">
        <b>Versión vigente 17/01/2022</b><br></br><br></br>
        
        Este contrato describe los términos y condiciones generales (los "Términos y Condiciones Generales") aplicables al uso de los servicios ofrecidos por <b>MARCA DEL E-COMMERCE</b>., CUIT 30-70308853-4, ("los Servicios") dentro del sitio <a href="http://cliente-pf-e-commerce.herokuapp.com">http://cliente-pf-e-commerce.herokuapp.com</a> ("<b>MARCA DEL E-COMMERCE</b>" o el "sitio"). Cualquier persona (en adelante "Usuario" o en plural "Usuarios") que desee acceder y/o usar el sitio o los Servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales respectivos, junto con todas las demás políticas y principios que rigen <b>MARCA DEL E-COMMERCE</b> y que son incorporados al presente por referencia.<br></br>
        <b>CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</b><br></br>
        El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad así como en los demás documentos incorporados a los mismos por referencia, previo a su registración como Usuario de <b>MARCA DEL E-COMMERCE</b>, optando de forma expresa por recibir los mismos y toda otra información por medios digitales.<br></br>
        <br></br>
        <b>01 - Capacidad</b><br></br><br></br>

        Los Servicios sólo están disponibles para personas que tengan capacidad legal para contratar. No podrán utilizar los servicios las personas que no tengan esa capacidad o Usuarios de <b>MARCA DEL E-COMMERCE</b> que hayan sido suspendidos temporalmente o inhabilitados definitivamente. Si estás registrando un Usuario como Empresa, debes tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este Acuerdo.<br></br>
        Los menores de edad, a partir de los 13 años, sólo podrán utilizar su cuenta con autorización del representante legal, quien responderá por todas las acciones y obligaciones que se deriven de la utilización de esa cuenta y quien. También deberá velar por el uso responsable y adecuado de ella en atención a la madurez del menor de edad que autorice.<br></br>
        <br></br>
        <b>02 - Registración</b><br></br><br></br>

        Es obligatorio completar el formulario de registración en todos sus campos con datos válidos para poder utilizar los servicios que brinda <b>MARCA DEL E-COMMERCE</b>. El futuro Usuario deberá completarlo con su información personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los Datos Personales conforme resulte necesario. El Usuario presta expresa conformidad con que <b>MARCA DEL E-COMMERCE</b> utiliza diversos medios para identificar sus datos personales, asumiendo el Usuario la obligación de revisarlos y mantenerlos actualizados. <b>MARCA DEL E-COMMERCE</b> NO se responsabiliza por la certeza de los Datos Personales de los Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de sus Datos Personales.<br></br>
        A su exclusiva discreción, <b>MARCA DEL E-COMMERCE</b> podrá requerir una registración adicional a los Usuarios que operen como concesionarias o inmobiliarias, como requisito para que dichos Usuarios accedan a paquetes especiales de publicaciones. En estos casos, una vez efectuada la registración adicional, las ofertas de venta de automóviles o inmuebles que realicen las concesionarias o inmobiliarias, respectivamente, sólo se publicarán en <b>MARCA DEL E-COMMERCE</b> a través de alguno de dichos paquetes o bajo las modalidades que <b>MARCA DEL E-COMMERCE</b> habilite para este tipo de Usuarios. <b>MARCA DEL E-COMMERCE</b> se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, así como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitación, se darán de baja todos los artículos publicados, así como las ofertas realizadas, sin que ello genere algún derecho a resarcimiento.<br></br>
        El Usuario accede a su cuenta personal("Cuenta") mediante el ingreso de su Apodo y clave de seguridad personal elegida ("Clave de Seguridad"). El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad.<br></br>
        La Cuenta es personal, única e intransferible, y está prohibido que un mismo Usuario registre o posea más de una Cuenta. En caso que <b>MARCA DEL E-COMMERCE</b> detecte distintas Cuentas que contengan datos coincidentes o relacionados, podrá cancelar, suspender o inhabilitarlas.<br></br>
        El Usuario será responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar a <b>MARCA DEL E-COMMERCE</b> en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión o transferencia de la Cuenta (incluyendo la reputación) bajo ningún título.<br></br>
        <b>MARCA DEL E-COMMERCE</b> se reserva el derecho de rechazar cualquier solicitud de registración o de cancelar una registración previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.<br></br>
        Ver políticas de inhabilitación o suspensión de usuario<br></br><br></br>
        <b>03 - Modificaciones del Acuerdo</b><br></br><br></br>
        <b>MARCA DEL E-COMMERCE</b> podrá modificar los Términos y Condiciones Generales en cualquier momento haciendo públicos en el Sitio los términos modificados. Todos los términos modificados entrarán en vigor a los 10 (diez) días de su publicación. Dichas modificaciones serán comunicadas por <b>MARCA DEL E-COMMERCE</b> a los usuarios que en la Configuración de su Cuenta de <b>MARCA DEL E-COMMERCE</b> hayan indicado que desean recibir notificaciones de los cambios en estos Términos y Condiciones. Todo usuario que no esté de acuerdo con las modificaciones efectuadas por <b>MARCA DEL E-COMMERCE</b> podrá solicitar la baja de la cuenta.<br></br>
        El uso del sitio y/o sus servicios implica la aceptación de estos Términos y Condiciones generales de uso de <b>MARCA DEL E-COMMERCE</b>.<br></br>
        <br></br>
        <b>04 - Listado de Bienes</b><br></br>
        <b>4.1 Utilización de Mercado Pago</b><br></br><br></br>
        Al publicar un anuncio en el Sitio, el usuario vendedor consiente expresamente la utilización de Mercado Pago como una de las formas disponibles para el pago del bien o servicio ofrecido y se obliga a no modificar en nada el precio de venta del bien o servicio si el comprador decidiera utilizar Mercado Pago. Asimismo, el usuario declara que ha leído, comprendido y aceptado los Términos y Condiciones de utilización de dicho servicio.<br></br>
        <br></br>
        <b>4.2 Publicación de bienes y/o servicios</b><br></br><br></br>
        El Usuario deberá ofrecer a la venta los bienes y promover los servicios en las categorías y subcategorías apropiadas. Las publicaciones podrán incluir textos descriptivos, gráficos, fotografías y otros contenidos y condiciones pertinentes para la venta del bien o la promoción del servicio, siempre que no violen ninguna disposición de este acuerdo o demás políticas de <b>MARCA DEL E-COMMERCE</b>. El bien o servicio ofrecido por el Usuario vendedor debe ser exactamente descrito en cuanto a sus condiciones y características relevantes. Se entiende y presume que mediante la inclusión del bien o servicio en <b>MARCA DEL E-COMMERCE</b>, el Usuario acepta que tiene la intención y el derecho de vender el bien u ofrecer el servicio referido, o está facultado para ello por su titular. Asimismo, el Usuario acepta que tiene disponible el bien publicado para su entrega inmediata o para el plazo especificado en la publicación, así como el servicio para su prestación en el plazo acordado. Se establece que los precios de los bienes o servicios publicados deberán ser expresados con IVA incluido cuando corresponda la aplicación del mismo, y en moneda de curso legal. <b>MARCA DEL E-COMMERCE</b> podrá remover cualquier publicación cuyo precio no sea expresado de esta forma para evitar confusiones o malentendidos en cuanto al precio final del bien o servicio. Se deja expresamente establecido que ninguna descripción podrá contener datos personales o de contacto, tales como, y sin limitarse a, números telefónicos, dirección de e-mail, dirección postal, direcciones de páginas de Internet que contengan datos como los mencionados anteriormente. Para determinados productos, <b>MARCA DEL E-COMMERCE</b> podrá requerir al vendedor que también realice su publicación a través de Publicaciones de Catálogo.<br></br>
        En las categorías Autos, Motos y Otros, Inmuebles y Servicios, los datos personales o de contacto deberán agregarse en la sección específicamente prevista para incluir la información sobre el vendedor o anunciante. No podrán publicitarse otros medios de pagos, distintos de los enunciados por <b>MARCA DEL E-COMMERCE</b> en la página de publicación de artículos, ni tampoco se podrá sugerir o insinuar a los compradores que no utilicen Mercado Pago y/o alterar las condiciones de compra si el Usuario comprador decidiera utilizar MercadoPago. <br></br>
        <br></br>
        <b>4.3 Licencia sobre imágenes, fotografías, marcas e Información de Producto</b><br></br>
        <br></br>
        El usuario autoriza a <b>MARCA DEL E-COMMERCE</b> y sus compañías asociadas a utilizar, publicar, reproducir y/o adaptar las imágenes y fotografías incluidas en sus publicaciones, su nombre comercial, marcas, frases publicitarias, logos, diseños, dibujos, imágenes y todo otro signo distintivo que identifique al Usuario y sus productos o servicios (la "Marca") e información de sus productos o servicios  ("Información de Producto"). Será obligación del Usuario incluir en las publicaciones  las imágenes, fotografías y Marca, así como la Información de Producto, de manera actualizada, incluyendo aquellas advertencias que sean requeridas por la legislación aplicable para la venta o publicidad de los productos y servicios . Conforme a lo anterior, <b>MARCA DEL E-COMMERCE</b> podrá obtener las imágenes, fotografías, Marca e Información de Producto directamente del Usuario, terceros autorizados por éste, o a través del sitio web del Usuario.<br></br>
        En particular, el Usuario otorga a <b>MARCA DEL E-COMMERCE</b> y a sus sociedades relacionadas una autorización gratuita, irrevocable, no exclusiva, internacional y sin límite temporal para usar, publicar, reproducir y/o adaptar las imágenes, fotografías, la Marca y la Información de Producto con el fin de ser usadas en todos los sitios y aplicaciones de <b>MARCA DEL E-COMMERCE</b>, redes sociales y/o en cualquier medio masivo y no masivo de comunicación, incluyendo sin limitación, plataformas y cualquier otro medio digital o físico que <b>MARCA DEL E-COMMERCE</b> considere oportuno o con aquellas otras plataformas o sitios de Internet con los cuales <b>MARCA DEL E-COMMERCE</b> haya realizado una alianza, para identificar ofertas, clasificar productos, crear catálogos, realizar acciones publicitarias y de marketing vinculadas a los servicios de <b>MARCA DEL E-COMMERCE</b>, incluyendo la posibilidad de asociación con  marcas y/o nombres comerciales de terceros, así como sublicenciar su uso a terceros, incluyendo, de manera enunciativa, más no limitativa,  facultades de uso, publicación, reproducción y adaptación de las imágenes, fotografías, Marca e Información de Producto en el marco de las Publicaciones de Catálogo.<br></br>
        El Usuario declara y garantiza que es titular o licenciatario de los derechos necesarios sobre las imágenes, fotografías contenidas en sus publicaciones, sobre las Marcas, así como sobre la Información de Producto, y que cuenta con los derechos y facultades necesarias para conceder la autorización detallada en esta cláusula, siendo responsable exclusivo por cualquier infracción a derechos de terceros o por las inconsistencias o inexactitud en la Información de Producto.<br></br>
        <b>MARCA DEL E-COMMERCE</b> podrá eliminar la publicación de las imágenes y fotografías, e incluso del bien o servicio, si interpretara, a su exclusivo criterio, que la imagen no cumple con los presentes Términos y Condiciones. Las imágenes y fotografías de bienes o servicios publicados bajo la modalidad Premium deberán cumplir con algunos requisitos adicionales como condición para ser expuestas en la Página Principal del Sitio Web. Conocé los requisitos.<br></br>
       
       <br></br>
        <b>4.4 Artículos Prohibidos</b><br></br>
        <br></br>

        Sólo podrán ser ingresados en las listas de bienes y servicios ofrecidos, aquellos cuya venta no se encuentre tácita o expresamente prohibida en los Términos y Condiciones Generales y demás políticas de <b>MARCA DEL E-COMMERCE</b> o por la ley vigente. Para obtener mayor información sobre bienes o servicios prohibidos, se pueden consultar nuestras Políticas de Artículos Prohibidos de <b>MARCA DEL E-COMMERCE</b>.<br></br>
        <br></br>
        <b>4.5 Brand Protection Program</b><br></br>
        <br></br>
        <b>MARCA DEL E-COMMERCE</b> ha desarrollado un Programa (en adelante, "BPP") destinado a brindar a los titulares de Propiedad Intelectual una herramienta para denunciar contenido en supuesta infracción a sus derechos. Los participantes del BPP, sean los titulares de derechos o sus apoderados, podrán identificar y solicitar la remoción de aquellas publicaciones que infrinjan sus derechos. En caso que <b>MARCA DEL E-COMMERCE</b> reciba una denuncia a través del BPP o un reclamo de un tercero o sospeche que se está cometiendo o se ha cometido una infracción a derechos de Propiedad Intelectual, <b>MARCA DEL E-COMMERCE</b> se reserva el derecho de adoptar todas las medidas que entienda adecuadas, lo que puede incluir la aplicación de sanciones sobre la cuenta y publicaciones del usuario, como también brindar datos personales del usuario, tal como se describe en las Políticas de Privacidad.<br></br>
        Los Usuarios entienden y aceptan que la responsabilidad por las denuncias, suspensión y eliminación de publicaciones realizadas a través de BPP es únicamente de los miembros del Programa.<br></br>
        Al solicitar la adhesión al BPP estarás aceptando los Términos y Condiciones del programa, y la información brindada tendrá carácter de declaración jurada.<br></br>
        <br></br>
        <b>05 - Privacidad de la Información</b><br></br>
        <br></br>
        Para utilizar los Servicios ofrecidos por <b>MARCA DEL E-COMMERCE</b>, los Usuarios deberán facilitar determinados datos de carácter personal. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica. Para mayor información sobre la privacidad de los Datos Personales y casos en los que será revelada la información personal, se pueden consultar nuestras Políticas de Privacidad.<br></br>
        <br></br>
        <b>06 - Obligaciones de los Usuarios</b><br></br>
        <b>6.1 Obligaciones del comprador</b><br></br>
        <br></br>
        Durante el plazo fijado por el Usuario vendedor, los Usuarios interesados realizarán ofertas de compra para los bienes y servicios que permitan la contratación en el Sitio y podrán contactar a los oferentes de las categorías Autos, Motos y Otros, Inmuebles y Servicios. La oferta de venta se cierra una vez que vence el plazo de la publicación o se acaban las cantidades estipuladas por el Vendedor y la promoción del servicio culmina con el vencimiento del plazo de la publicación.<br></br>
        El Comprador está obligado a intentar comunicarse con el vendedor y completar la operación si ha realizado una oferta por un artículo salvo que la operación esté prohibida por la ley o los Términos y Condiciones Generales y demás políticas de <b>MARCA DEL E-COMMERCE</b>, en cuyo caso no estará obligado a concretar la operación.<br></br>
        Al ofertar por un bien o contratar un servicio, el Usuario acepta quedar obligado por las condiciones de venta incluidas en la publicación, en la medida en que las mismas no infrinjan las leyes o los Términos y Condiciones Generales y demás políticas de <b>MARCA DEL E-COMMERCE</b>. La oferta de compra de un bien o contratación de un servicio es irrevocable salvo en circunstancias excepcionales, tales como que el vendedor cambie sustancialmente la descripción del bien o servicio después de realizada alguna oferta, que exista un claro error tipográfico, o que no pueda verificar la identidad del vendedor.<br></br>
        Las ofertas de compra sólo serán consideradas válidas una vez que hayan sido procesadas por el sistema informático de <b>MARCA DEL E-COMMERCE</b>.<br></br>
        Ante cualquier inconveniente, el usuario comprador podrá iniciar un reclamo en el Sitio contra su vendedor, dentro de los 60 días de realizada la compra.<br></br>
        Impuestos. Tal como lo establece la normativa fiscal vigente, el comprador debe exigir factura o ticket al vendedor como comprobante de la operación. El vendedor no estará obligado a emitir factura o ticket sólo en el caso de tratarse de una persona física que efectúa ventas ocasionalmente.<br></br>
        <br></br>
        <b>6.2. Obligaciones del vendedor</b><br></br>
        <br></br>
        El usuario vendedor debe tener capacidad legal para vender el bien o servicio objeto de su oferta. Asimismo, debe cumplir con todas las obligaciones regulatorias pertinentes y contar con los registros, habilitaciones, permisos y/o autorizaciones exigidos por la normativa aplicable para la venta de los bienes y servicios ofrecidos. Si el usuario vendedor ha recibido una oferta queda obligado a intentar comunicarse con el comprador y completar la operación. La cancelación de una venta por parte del Usuario vendedor impactará en su reputación. Aquel Usuario vendedor que tenga un porcentaje de ventas canceladas igual o superior a 2,5%, podrá ser advertido, suspendido y/o inhabilitado por <b>MARCA DEL E-COMMERCE</b> para continuar operando en el sitio.<br></br>
        <b>MARCA DEL E-COMMERCE</b> tendrá el derecho de requerir, conforme los criterios que considere pertinentes, que ciertos usuarios vendedores solamente anuncien sus bienes o servicios en el Sitio Web mediante la utilización de los Servicios de Gestión de Pagos online de Mercado Pago y/o otras herramientas ofrecidas por <b>MARCA DEL E-COMMERCE</b> para el cobro del bien vendido y de las tarifas por la utilización de los servicios, importando eventualmente en el pago de tarifas aplicables por la utilización de los mismos.<br></br>
        Dado que <b>MARCA DEL E-COMMERCE</b> es un punto de encuentro entre comprador y vendedor y no participa de las operaciones que se realizan entre ellos, el vendedor será responsable por todas las obligaciones y cargas impositivas que correspondan por la venta de sus bienes y/o servicios, sin que pudiera imputarse a <b>MARCA DEL E-COMMERCE</b> algún tipo de responsabilidad por incumplimientos en tal sentido.<br></br>
        En virtud de lo dispuesto por la Secretaría de Comercio del Interior mediante Resolución 244/2020, los usuarios vendedores están obligados a informar a los usuarios compradores que los plazos previstos en las garantías contractuales y legales quedan suspendidos por todo el periodo en que no puedan ejercer sus derechos en virtud del Aislamiento Social, Preventivo y Obligatorio dictado por el Decreto 297/2020 y sus modificatorios.<br></br>
        Impuestos. Como se menciona anteriormente, <b>MARCA DEL E-COMMERCE</b> sólo pone a disposición de los usuarios un espacio virtual que les permite comunicarse mediante Internet para encontrar una forma de vender o comprar artículos y/o servicios. <b>MARCA DEL E-COMMERCE</b> no tiene participación alguna en el proceso de negociación y perfeccionamiento del contrato definitivo entre las partes. Por eso, <b>MARCA DEL E-COMMERCE</b> no es responsable por el efectivo cumplimiento de las obligaciones fiscales o impositivas establecidas por la ley vigente.<br></br>
        El vendedor acepta que su comprador puede revocar la compra dentro de un plazo de 10 días desde que recibe el producto. Asimismo, el vendedor acepta que los compradores podrán pedir la devolución del producto en los términos de los programas de Compra Protegida, Mercado Puntos y demás Anexos, hasta 30 días después de la recepción del producto. En cualquiera de los mencionados casos, el vendedor deberá aceptar la devolución del producto vendido y deberá hacerse cargo de los gastos que esto conlleve, incluyendo los costos de envío que fueren necesarios. En la categoría de Servicios, el vendedor acepta que el precio será reintegrado a su comprador cuando el servicio contratado no sea efectivamente prestado o sea cancelado hasta la fecha en que debió prestarse. <b>MARCA DEL E-COMMERCE</b> podrá debitar estos costos de la cuenta de Mercado Pago del vendedor.<br></br>
        <b>MARCA DEL E-COMMERCE</b> podrá disponibilizar etiquetas de envíos para que el comprador realice la devolución y debitar el costo de la misma en la cuenta de Mercado Pago del vendedor.<br></br>
        <br></br>
        <b>07 - Prohibiciones</b><br></br>
        <br></br>
        Los usuarios no podrán: (a) manipular los precios de los artículos; (b) mantener cualquier tipo de comunicación por otro medio distinto al servicio de mensajería que ofrece <b>MARCA DEL E-COMMERCE</b> (incluyendo mails, redes sociales, WhatsApp, etc) ya sea durante la oferta del bien o con posterioridad a ella, salvo en la sección de Preguntas y Respuestas y en las categorías Autos, Motos y Otros, Servicios e Inmuebles y Propiedades que así lo permitan; (c) dar a conocer sus datos personales o de otros usuarios a través de la sección de Preguntas y Respuestas y/o por algún otro medio (incluyendo pero sin limitar Twitter, Facebook y/ o cualquier otra red social), salvo en las categorías Autos, Motos y Otros e Inmuebles y Propiedades que así lo permitan; (d) aceptar datos personales proporcionados por otros usuarios a través de la sección de Preguntas y Respuestas y/o algún otro medio (incluyendo pero sin limitar Twitter, Facebook y/o cualquier otra red social); (e) publicar o vender artículos prohibidos por los Términos y Condiciones Generales, demás políticas de <b>MARCA DEL E-COMMERCE</b> o leyes vigentes; (f) insultar, discriminar o agredir a otros Usuarios, colaboradores de <b>MARCA DEL E-COMMERCE</b> o cualquier persona que esté relacionada a los servicios que <b>MARCA DEL E-COMMERCE</b> presta en su plataforma; (g) utilizar su reputación, calificaciones o comentarios recibidos en el sitio de <b>MARCA DEL E-COMMERCE</b> en cualquier ámbito fuera de <b>MARCA DEL E-COMMERCE</b>; (h) publicar artículos idénticos en más de una publicación.<br></br>
        Este tipo de actividades será investigado por <b>MARCA DEL E-COMMERCE</b> y el infractor podrá ser sancionado con la suspensión o cancelación de la oferta e incluso de su inscripción como usuario de <b>MARCA DEL E-COMMERCE</b> y/o de cualquier otra forma que estime pertinente, sin perjuicio de las acciones legales a que pueda dar lugar por la configuración de delitos o contravenciones o los perjuicios civiles que pueda causar a los usuarios oferentes.<br></br>
        <br></br>
        <b>08 - Violaciones del Sistema o Bases de Datos</b><br></br>
        <br></br>
        No está permitida ninguna acción o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de <b>MARCA DEL E-COMMERCE</b> como en las ofertas, descripciones, cuentas o bases de datos de <b>MARCA DEL E-COMMERCE</b>. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.<br></br>
        <br></br>
        <b>09 - Sanciones. Suspensión de operaciones</b><br></br>
        <br></br>
        Sin perjuicio de otras medidas, <b>MARCA DEL E-COMMERCE</b> podrá advertir, suspender en forma temporal o definitivamente la Cuenta de un Usuario o una publicación, aplicar una sanción que impacte negativamente en la reputación de un Usuario, iniciar las acciones que estime pertinentes y/o suspender la prestación de sus Servicios si (a) se quebrantara alguna ley, o cualquiera de las estipulaciones de los Términos y Condiciones Generales y demás políticas de <b>MARCA DEL E-COMMERCE</b>; (b) si incumpliera sus compromisos como Usuario; (c) si se incurriera a criterio de <b>MARCA DEL E-COMMERCE</b> en conductas o actos dolosos o fraudulentos; (d) no pudiera verificarse la identidad del Usuario o cualquier información proporcionada por el mismo fuere errónea; (e) <b>MARCA DEL E-COMMERCE</b> entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las publicó, para <b>MARCA DEL E-COMMERCE</b> o para los demás Usuarios en general. En el caso de la suspensión de un Usuario, sea temporal o definitiva, todos los artículos que tuviera publicados serán removidos del sistema.<br></br>
        <br></br>
        <b>10 - Responsabilidad</b><br></br>
        <br></br>
        <b>MARCA DEL E-COMMERCE</b> pone a disposición de los Usuarios un espacio virtual que les permite ponerse en comunicación para ofrecer, vender y/o comprar bienes y servicios.<br></br>
        Son los Usuarios Vendedores quienes utilizan <b>MARCA DEL E-COMMERCE</b> para publicar sus productos y servicios, y definir las condiciones de su oferta (producto o servicio ofrecido, precio, descripción, fotos, calidad, cantidad, integridad, etc.).<br></br>
        En todos los casos, al ser los Usuarios Vendedores los propietarios de los productos publicados y quienes los ofrecen para su venta, serán responsables por la existencia, calidad, cantidad, integridad o legitimidad de los productos o servicios que ofrecen, y mantendrán indemnes a <b>MARCA DEL E-COMMERCE</b> por las eventuales acciones o reclamaciones que pudiesen surgir con motivo de una oferta o transacción.<br></br>
        <br></br>
        <b>11 - Alcance de los servicios de <b>MARCA DEL E-COMMERCE</b></b><br></br>
        <br></br>
        Este acuerdo no crea ningún contrato de sociedad, de mandato, de franquicia, o relación laboral entre <b>MARCA DEL E-COMMERCE</b> y el usuario. El usuario reconoce y acepta que <b>MARCA DEL E-COMMERCE</b> no es parte en ninguna operación, ni tiene control alguno sobre la calidad, seguridad o legalidad de los bienes y servicios anunciados, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para vender o comprar artículos. <b>MARCA DEL E-COMMERCE</b> no puede asegurar que un usuario completará una operación ni podrá verificar la identidad o datos personales ingresados por los usuarios. <b>MARCA DEL E-COMMERCE</b> no garantiza la veracidad de la publicidad de terceros que aparezca en el sitio y no será responsable por la correspondencia o contratos que el usuario celebre con dichos terceros o con otros usuarios.<br></br>
        De igual forma, el usuario reconoce y acepta que <b>MARCA DEL E-COMMERCE</b> no es parte, no interviene ni tiene control alguno sobre los servicios de protección extendida que son comercializados y prestados en forma exclusiva por Assurant Services Argentina S.A.<br></br>
        
        <br></br>
        <b>12 - Fallas en el sistema</b><br></br>
        <br></br>
        <b>MARCA DEL E-COMMERCE</b> no se responsabiliza por cualquier daño, perjuicio o pérdida al usuario causados por fallas en el sistema, en el servidor o en Internet. <b>MARCA DEL E-COMMERCE</b> tampoco será responsable por cualquier virus que pudiera infectar el equipo del usuario como consecuencia del acceso, uso o examen de su sitio web o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenidos en el mismo. Los usuarios NO podrán imputar responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas o fallas en los sistemas o en Internet. <b>MARCA DEL E-COMMERCE</b> no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otra circunstancia ajena a <b>MARCA DEL E-COMMERCE</b>; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputarse algún tipo de responsabilidad. <b>MARCA DEL E-COMMERCE</b> no será responsable por ningún error u omisión de contenidos en su sitio web.<br></br>
        
        <br></br>
        <b>13 - Tarifas. Facturación</b><br></br>
        <br></br>
        El usuario vendedor solo deberá pagar a <b>MARCA DEL E-COMMERCE</b> un costo por la venta cuando la operación se concrete, o si no la cancela antes de los 21 días después de recibir la oferta. Para el caso correspondiente a la categoría Autos, Motos y Otros, Servicios e Inmuebles, el usuario solamente deberá pagar a <b>MARCA DEL E-COMMERCE</b> únicamente un costo por publicar, salvo en aquellos Servicios que permitan la contratación en el Sitio y sujeto a la modalidad de publicación elegida.<br></br>
        <b>MARCA DEL E-COMMERCE</b> se reserva el derecho de tomar las medidas judiciales y extrajudiciales que estime pertinentes para obtener el pago del monto debido.<br></br>
        <b>MARCA DEL E-COMMERCE</b> se reserva el derecho de modificar, cambiar, agregar, o eliminar las tarifas vigentes, en cualquier momento, lo cual será notificado a los Usuarios, en la forma establecida en la Cláusula 3. Sin embargo, <b>MARCA DEL E-COMMERCE</b> podrá modificar temporalmente la Política de Tarifas y las tarifas por sus servicios por razón de promociones, siendo efectivas estas modificaciones cuando se haga pública la promoción o se realice el anuncio.<br></br>
        En caso de haberse facturado cargos que no hubiesen correspondido, el usuario deberá comunicarse con nuestro equipo de Atención al Cliente para resolver dicha cuestión.<br></br>
        Conoce más sobre nuestras Políticas de Facturación.<br></br>
        
        <br></br>
        <b>14 - Sistema de reputación</b><br></br>
        <br></br>
        Debido a que la verificación de la identidad de los Usuarios en Internet es difícil, <b>MARCA DEL E-COMMERCE</b> no puede confirmar ni confirmar la identidad pretendida de cada Usuario. Por ello el Usuario Vendedor cuenta con un sistema de reputación de Usuarios que es actualizado periódicamente en base a datos vinculados con su actividad en el sitio. Este sistema de reputación, además constará de un espacio donde los Usuarios compradores podrán hacer comentarios sobre la experiencia de compra. Dichos comentarios serán incluidos bajo exclusiva responsabilidad de los Usuarios que los emitan.<br></br>
        <b>MARCA DEL E-COMMERCE</b> no tiene obligación de verificar la veracidad o exactitud de los mismos y NO se responsabiliza por los dichos allí vertidos por cualquier Usuario, por las ofertas de compras o ventas que los Usuarios realicen teniéndolos en cuenta o por la confianza depositada en las opiniones de los compradores o por cualquier otro comentario expresado dentro del sitio o a través de cualquier otro medio incluido el correo electrónico. <b>MARCA DEL E-COMMERCE</b> se reserva el derecho de editar y/o eliminar aquellos comentarios que sean considerados inadecuados u ofensivos. <b>MARCA DEL E-COMMERCE</b> mantiene el derecho de excluir a aquellos Usuarios que sean objeto de comentarios negativos provenientes de fuentes distintas.<br></br>
        
        <br></br>
        <b>15 - Propiedad intelectual - Licencia - Enlaces</b><br></br>
        <br></br>
        <b>MARCA DEL E-COMMERCE</b> y/o sus sociedades controlantes, controladas, filiales o subsidiarias se reservan todos los derechos, incluyendo los derechos de propiedad intelectual e industrial, asociados con los servicios de <b>MARCA DEL E-COMMERCE</b>, sus sitios web, los contenidos de sus pantallas, programas, bases de datos, redes, códigos, desarrollo, software, arquitectura, hardware, contenidos, información, tecnología, fases de integración, funcionalidades, dominios, archivos que permiten al Usuario acceder y crear su Cuenta, herramientas de venta, marcas, patentes, derechos de autor, diseños y modelos industriales, nombres comerciales, entre otros, y declara que están protegidos por leyes nacionales e internacionales vigentes.<br></br>
        En ningún caso se entenderá que el Usuario tendrá algún tipo de derecho sobre los mismos excepto para utilizar el servicio de <b>MARCA DEL E-COMMERCE</b> conforme a lo previsto en estos Términos y Condiciones Generales. El uso indebido o contrario a la normativa vigente de los derechos de propiedad intelectual e industrial de <b>MARCA DEL E-COMMERCE</b>, así como su reproducción total o parcial, queda prohibido, salvo autorización expresa y por escrito de <b>MARCA DEL E-COMMERCE</b>.<br></br>
        Los Usuarios tampoco podrán comunicar que los productos o servicios que ofrecen son patrocinados, promovidos, producidos, ofrecidos y/o vendidos por <b>MARCA DEL E-COMMERCE</b> y deberán abstenerse de realizar cualquier acto que pudiera causar un daño, pérdida de reputación, o disminución del valor de los derechos de propiedad intelectual e industrial de <b>MARCA DEL E-COMMERCE</b>.<br></br>
        El sitio puede contener enlaces a sitios web de terceros. En virtud que <b>MARCA DEL E-COMMERCE</b> no tiene control sobre tales sitios, no será responsable por los contenidos, materiales, acciones y/o servicios prestados por los mismos, ni por daños o pérdidas ocasionadas por la utilización de éstos, causados directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relación, aprobación, respaldo de <b>MARCA DEL E-COMMERCE</b> con dichos sitios y sus contenidos.<br></br>

        <br></br>
        <b>16 - Indemnidad</b><br></br>
        <br></br>
        El Usuario mantendrá indemne a <b>MARCA DEL E-COMMERCE</b>, así como a sus filiales, empresas controladas y/o controlantes, funcionarios, directivos, sucesores, administradores, representantes y empleados, por cualquier reclamo iniciado por otros Usuarios, terceros o por cualquier Organismo, relacionado con sus actividades en el Sitio, el cumplimiento y/o el incumplimiento de los Términos y Condiciones Generales o demás Políticas, así como respecto de cualquier violación de leyes o derechos de terceros.<br></br>
        A tal fin, el Usuario faculta a <b>MARCA DEL E-COMMERCE</b> a: i) intervenir y representarlo en dichos reclamos, pudiendo celebrar los acuerdos transaccionales que considere oportunos y que tiendan a evitar mayores costos y/o evitar eventuales contingencias sin limitación, en su nombre y representación; ii) retener y debitar de su Cuenta de Mercado Pago y/o de la(s) cuenta(s) bancaria(s) registrada(s) en la Cuenta Mercado Pago los fondos existentes y/o futuros para recuperar cualquier gasto incurrido en relación a los supuestos del párrafo anterior, los cuales podrán incluir, entre otros, los honorarios de los letrados intervinientes y las costas judiciales en una cantidad razonable, y/o iii) generar débitos específicos en su facturación.<br></br>
        
        <br></br>
        <b>17 - Jurisdicción y Ley Aplicable</b><br></br>
        <br></br>
        Este acuerdo estará regido en todos sus puntos por las leyes vigentes en la República Argentina.<br></br>
        Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretación, alcance o cumplimiento, será sometida ante la Justicia Nacional Ordinaria salvo disposición específica de normas de Orden Público, como por ejemplo la Ley de Defensa del Consumidor (o normativa vinculada) en los casos en los que ésta sea aplicable.<br></br>
        
        <br></br>
        <b>18 - Domicilio</b><br></br>
        <br></br>
        Se fija como domicilio de <b>MARCA DEL E-COMMERCE</b> S.R.L. la avenida Caseros 3039, piso 2, Capital Federal, código postal C1264, República Argentina.<br></br>
        Si tienes alguna duda sobre los Términos y Condiciones Generales o demás políticas y principios que rigen <b>MARCA DEL E-COMMERCE</b> consulta nuestra página de Ayuda.<br></br>

      </p>

      <div className='termfooter'><Footer /></div>
    </div>
  )
}

export default TerminosYCondiciones;
